type AdminLocale = 'en' | 'ar'

const adminCopy = {
  en: {
    sidebar: {
      pipeline: 'Pipeline',
      tasks: 'Smart Tasks',
      settings: 'Settings',
      visitSite: 'Visit Site',
      administrator: 'Administrator',
      signOut: 'Sign out',
    },
    pages: {
      accessDeniedTitle: 'Access Denied',
      accessDeniedBody: 'Your account does not have administrative privileges.',
      accessDeniedAdminLayout: "Your account doesn't have the permissions required to enter the command center.",
      signOutTryAnother: 'Sign out and try another',
      backToDashboard: 'Back to Dashboard',
      backToPipeline: 'Back to Pipeline',
      saveSettings: 'Save Settings',
      savingSettings: 'Saving Settings...',
      settingsSaved: 'Settings updated successfully!',
      settingsError: 'Error saving settings: ',
      settingsTitle: 'Admin Settings',
      settingsSubtitle: 'Control booking defaults, reminder timings, and marketing configuration from one place.',
    },
    settings: {
      bookingTitle: 'Booking Defaults',
      marketingTitle: 'Marketing Config',
      adminEmail: 'Admin notification email',
      bookingTimezone: 'Default booking timezone',
      bookingStart: 'First booking hour',
      bookingEnd: 'Last booking hour',
      bookingSlot: 'Slot length (minutes)',
      bookingNotice: 'Minimum notice (minutes)',
      bookingWindow: 'Booking day window',
      reminderLead: 'Reminder lead time (minutes)',
      pixelId: 'Facebook Pixel ID',
      pixelToken: 'Facebook Conversions API Token',
      optional: 'Optional',
      adminEmailHint: 'Fallback inbox for booking alerts and ops notifications.',
      bookingTimezoneHint: 'Used as the default scheduling timezone for admin reschedules.',
      bookingHoursHint: 'These values define the default scheduling window in the public booking modal.',
      bookingNoticeHint: 'Prevents last-minute bookings that give the team no prep time.',
      reminderHint: 'Operational default for how far in advance reminders should be sent.',
      pixelHint: 'The primary Pixel ID used to track PageViews and Leads.',
    },
    dashboard: {
      title: 'Lead Pipeline',
      subtitle: 'Live board for lead flow, meeting ops, and prep work.',
      searchPlaceholder: 'Search name, company, email, WhatsApp, notes, or message',
      searchLabel: 'Search',
      assigneeLabel: 'Assignee',
      sourceLabel: 'Source',
      focusLabel: 'Focus',
      focusAll: 'All leads',
      focusToday: "Today's calls",
      focusUpcoming: 'Upcoming meetings',
      focusNeedsLink: 'Needs meeting link',
      allAssignees: 'All assignees',
      unassigned: 'Unassigned',
      allSources: 'All sources',
      direct: 'Direct',
      website: 'Website',
      leadSourceDefault: 'website',
      sourceUnknown: 'Unknown source',
      totalLeads: 'Total leads',
      todayCalls: "Today's calls",
      unassignedCount: 'Unassigned',
      upcoming: 'Upcoming',
      nearestTasksTitle: 'Nearest Meeting Action List',
      nearestTasksBody: 'Only pending tasks are shown here so the next call stays actionable.',
      noUpcomingMeeting: 'No upcoming meeting found. As soon as a lead has the nearest future meeting, this panel will build its checklist automatically.',
      noPendingTasks: 'No pending tasks for this meeting.',
      quickNotes: 'Quick Notes',
      saveNotes: 'Save Notes',
      saving: 'Saving...',
      meeting: 'Meeting',
      startsIn: 'Starts in',
      startedAgo: 'Started',
      timePending: 'Time pending',
      email: 'Email',
      whatsapp: 'WhatsApp',
      brief: 'Brief',
      sendEmail: 'Send Email',
      sending: 'Sending...',
      sendReminder: 'Send Reminder',
      sendMeetingLink: 'Send Meeting Link',
      meetingUrlPlaceholder: 'Meeting URL...',
      sendLink: 'Send Link',
      nearestMeet: 'Nearest Meet',
      addTask: 'Add Task',
      taskTitle: 'Task title',
      taskOverview: 'Overview / notes / summary',
      adding: 'Adding...',
      addTaskButton: 'Add Task',
      seeFullDetails: 'See Full Details',
      communicationHistory: 'Communication History',
      noCommunications: 'No automated communications sent yet.',
      noInternalNotes: 'No internal notes captured yet.',
      projectType: 'Project Type',
      budgetRange: 'Budget Range',
      initialRequest: 'Initial Request',
      internalNotes: 'Internal Notes',
      operations: 'Operations',
      assignment: 'Assignment',
      meetingOps: 'Meeting Ops',
      status: 'Meeting status',
      stage: 'Pipeline stage',
      currentStage: 'Current stage',
      clientTimezone: 'Client timezone',
      reschedule: 'Reschedule',
      notifyClient: 'Notify client by email',
      meetingDate: 'Meeting date',
      meetingTime: 'Meeting time',
      saveChanges: 'Save Changes',
      cancelMeeting: 'Cancel meeting',
      markNoShow: 'Mark no-show',
      markCompleted: 'Mark completed',
      markScheduled: 'Mark scheduled',
      meetingLink: 'Meeting link',
      linkNotSet: 'No meeting link saved yet.',
      saveMeetingLink: 'Save meeting link',
      clientLocale: 'Client locale',
      details: 'Details',
      filtersApplied: 'filters applied',
      clearFilters: 'Clear filters',
      noLeads: 'No leads match the current filters.',
      notesSaved: 'Notes saved.',
      leadUpdated: 'Lead updated.',
      meetingRescheduled: 'Meeting rescheduled.',
      meetingCancelled: 'Meeting cancelled.',
      meetingCompleted: 'Meeting marked completed.',
      meetingNoShow: 'Lead marked as no-show.',
      reminderSent: 'Reminder sent successfully.',
      meetingLinkSent: 'Meeting link sent successfully.',
      saveLinkFirst: 'Please enter a meeting link',
      invalidMeetingLink: 'Meeting link must be a valid URL',
      sourcePlaceholder: 'Lead source',
      assigneePlaceholder: 'owner@company.com',
      noAssignee: 'No assignee',
      taskWorkspace: 'Task Workspace',
      openWorkspace: 'Open Workspace',
      deleteTask: 'Delete Task',
      markComplete: 'Mark Complete',
      saveTask: 'Save Task',
      addFullNotesPlaceholder: 'Add the full overview, analysis, talking points, summary, or client-facing notes here.',
      taskBriefFallback: 'No task overview yet. Open workspace to add your notes, summary, or client-facing brief.',
      detailFallback: 'No overview added yet. Open the workspace to write the full call brief, summary, or client-facing preparation notes.',
      taskMeetingContext: 'Meeting Context',
      completed: 'completed',
      scheduled: 'scheduled',
      reminder_status: 'reminder sent',
      link_sent: 'link sent',
      cancelled: 'cancelled',
      no_show: 'no-show',
    },
  },
  ar: {
    sidebar: {
      pipeline: 'مسار العملاء',
      tasks: 'المهام الذكية',
      settings: 'الإعدادات',
      visitSite: 'زيارة الموقع',
      administrator: 'المدير',
      signOut: 'تسجيل الخروج',
    },
    pages: {
      accessDeniedTitle: 'تم رفض الوصول',
      accessDeniedBody: 'حسابك لا يملك صلاحيات الإدارة.',
      accessDeniedAdminLayout: 'حسابك لا يملك الصلاحيات المطلوبة للدخول إلى لوحة التحكم.',
      signOutTryAnother: 'سجل الخروج وجرب حساباً آخر',
      backToDashboard: 'العودة إلى اللوحة',
      backToPipeline: 'العودة إلى المسار',
      saveSettings: 'حفظ الإعدادات',
      savingSettings: 'جارٍ حفظ الإعدادات...',
      settingsSaved: 'تم تحديث الإعدادات بنجاح!',
      settingsError: 'حدث خطأ أثناء حفظ الإعدادات: ',
      settingsTitle: 'إعدادات الإدارة',
      settingsSubtitle: 'تحكم في إعدادات الحجز والتنبيهات والتتبع من مكان واحد.',
    },
    settings: {
      bookingTitle: 'إعدادات الحجز الافتراضية',
      marketingTitle: 'إعدادات التسويق',
      adminEmail: 'بريد تنبيهات الإدارة',
      bookingTimezone: 'المنطقة الزمنية الافتراضية للحجز',
      bookingStart: 'أول ساعة حجز',
      bookingEnd: 'آخر ساعة حجز',
      bookingSlot: 'مدة الموعد بالدقائق',
      bookingNotice: 'الحد الأدنى قبل الحجز بالدقائق',
      bookingWindow: 'عدد الأيام المعروضة للحجز',
      reminderLead: 'وقت التذكير قبل الاجتماع بالدقائق',
      pixelId: 'معرف Facebook Pixel',
      pixelToken: 'رمز Facebook Conversions API',
      optional: 'اختياري',
      adminEmailHint: 'صندوق البريد الاحتياطي لتنبيهات الحجوزات والتنبيهات التشغيلية.',
      bookingTimezoneHint: 'تُستخدم كمنطقة زمنية افتراضية عند إعادة جدولة الاجتماعات من لوحة الإدارة.',
      bookingHoursHint: 'تحدد هذه القيم نافذة الحجز الافتراضية في نموذج الحجز العام.',
      bookingNoticeHint: 'تمنع الحجوزات المتأخرة التي لا تترك للفريق وقتاً للتحضير.',
      reminderHint: 'القيمة التشغيلية الافتراضية لوقت إرسال التذكيرات قبل الاجتماع.',
      pixelHint: 'المعرف الأساسي المستخدم لتتبع PageViews و Leads.',
    },
    dashboard: {
      title: 'مسار العملاء',
      subtitle: 'لوحة مباشرة لإدارة تدفق العملاء والاجتماعات والتحضير.',
      searchPlaceholder: 'ابحث بالاسم أو الشركة أو البريد أو واتساب أو الملاحظات أو الرسالة',
      searchLabel: 'بحث',
      assigneeLabel: 'المسؤول',
      sourceLabel: 'المصدر',
      focusLabel: 'التركيز',
      focusAll: 'كل العملاء',
      focusToday: 'اجتماعات اليوم',
      focusUpcoming: 'الاجتماعات القادمة',
      focusNeedsLink: 'تحتاج رابط اجتماع',
      allAssignees: 'كل المسؤولين',
      unassigned: 'غير مخصص',
      allSources: 'كل المصادر',
      direct: 'مباشر',
      website: 'الموقع',
      leadSourceDefault: 'website',
      sourceUnknown: 'مصدر غير معروف',
      totalLeads: 'إجمالي العملاء',
      todayCalls: 'اجتماعات اليوم',
      unassignedCount: 'غير مخصص',
      upcoming: 'القادمة',
      nearestTasksTitle: 'قائمة تجهيز أقرب اجتماع',
      nearestTasksBody: 'تظهر هنا المهام غير المكتملة فقط حتى يبقى الاجتماع القادم قابلاً للتنفيذ.',
      noUpcomingMeeting: 'لا يوجد اجتماع قادم حالياً. بمجرد وجود أقرب اجتماع مستقبلي سيتم إنشاء القائمة تلقائياً.',
      noPendingTasks: 'لا توجد مهام معلقة لهذا الاجتماع.',
      quickNotes: 'ملاحظات سريعة',
      saveNotes: 'حفظ الملاحظات',
      saving: 'جارٍ الحفظ...',
      meeting: 'الاجتماع',
      startsIn: 'يبدأ خلال',
      startedAgo: 'بدأ منذ',
      timePending: 'الوقت غير محدد',
      email: 'البريد الإلكتروني',
      whatsapp: 'واتساب',
      brief: 'الملخص',
      sendEmail: 'إرسال بريد',
      sending: 'جارٍ الإرسال...',
      sendReminder: 'إرسال تذكير',
      sendMeetingLink: 'إرسال رابط الاجتماع',
      meetingUrlPlaceholder: 'رابط الاجتماع...',
      sendLink: 'إرسال الرابط',
      nearestMeet: 'أقرب اجتماع',
      addTask: 'إضافة مهمة',
      taskTitle: 'عنوان المهمة',
      taskOverview: 'نظرة عامة / ملاحظات / ملخص',
      adding: 'جارٍ الإضافة...',
      addTaskButton: 'إضافة مهمة',
      seeFullDetails: 'عرض التفاصيل الكاملة',
      communicationHistory: 'سجل التواصل',
      noCommunications: 'لم يتم إرسال أي رسائل آلية بعد.',
      noInternalNotes: 'لا توجد ملاحظات داخلية حتى الآن.',
      projectType: 'نوع المشروع',
      budgetRange: 'الميزانية',
      initialRequest: 'الطلب الأولي',
      internalNotes: 'الملاحظات الداخلية',
      operations: 'العمليات',
      assignment: 'التخصيص',
      meetingOps: 'إدارة الاجتماع',
      status: 'حالة الاجتماع',
      stage: 'مرحلة المسار',
      currentStage: 'المرحلة الحالية',
      clientTimezone: 'المنطقة الزمنية للعميل',
      reschedule: 'إعادة الجدولة',
      notifyClient: 'إشعار العميل بالبريد الإلكتروني',
      meetingDate: 'تاريخ الاجتماع',
      meetingTime: 'وقت الاجتماع',
      saveChanges: 'حفظ التغييرات',
      cancelMeeting: 'إلغاء الاجتماع',
      markNoShow: 'تحديد كعدم حضور',
      markCompleted: 'تحديد كمكتمل',
      markScheduled: 'تحديد كمجدول',
      meetingLink: 'رابط الاجتماع',
      linkNotSet: 'لم يتم حفظ رابط الاجتماع بعد.',
      saveMeetingLink: 'حفظ رابط الاجتماع',
      clientLocale: 'لغة العميل',
      details: 'التفاصيل',
      filtersApplied: 'فلاتر مفعلة',
      clearFilters: 'مسح الفلاتر',
      noLeads: 'لا توجد عملاء يطابقون الفلاتر الحالية.',
      notesSaved: 'تم حفظ الملاحظات.',
      leadUpdated: 'تم تحديث العميل.',
      meetingRescheduled: 'تمت إعادة جدولة الاجتماع.',
      meetingCancelled: 'تم إلغاء الاجتماع.',
      meetingCompleted: 'تم تحديد الاجتماع كمكتمل.',
      meetingNoShow: 'تم تحديد العميل كعدم حضور.',
      reminderSent: 'تم إرسال التذكير بنجاح.',
      meetingLinkSent: 'تم إرسال رابط الاجتماع بنجاح.',
      saveLinkFirst: 'يرجى إدخال رابط الاجتماع',
      invalidMeetingLink: 'يجب أن يكون رابط الاجتماع صالحاً',
      sourcePlaceholder: 'مصدر العميل',
      assigneePlaceholder: 'owner@company.com',
      noAssignee: 'غير مخصص',
      taskWorkspace: 'مساحة عمل المهمة',
      openWorkspace: 'فتح مساحة العمل',
      deleteTask: 'حذف المهمة',
      markComplete: 'تحديد كمكتملة',
      saveTask: 'حفظ المهمة',
      addFullNotesPlaceholder: 'أضف هنا التحليل الكامل أو النقاط المهمة أو الملخص أو الملاحظات التي ستُشارك مع العميل.',
      taskBriefFallback: 'لا يوجد ملخص للمهمة بعد. افتح مساحة العمل لإضافة الملاحظات أو الملخص أو التحضير الخاص بالعميل.',
      detailFallback: 'لا يوجد وصف بعد. افتح مساحة العمل لكتابة ملخص المكالمة أو التحضير الكامل.',
      taskMeetingContext: 'سياق الاجتماع',
      completed: 'مكتمل',
      scheduled: 'مجدول',
      reminder_status: 'تم إرسال التذكير',
      link_sent: 'تم إرسال الرابط',
      cancelled: 'ملغي',
      no_show: 'عدم حضور',
    },
  },
} as const

export function getAdminCopy(locale: string) {
  return adminCopy[(locale === 'ar' ? 'ar' : 'en') as AdminLocale]
}
