declare module 'lucide-react' {
  import { FC } from 'react'
  export type Icon = FC<{ size?: number | string; className?: string; color?: string; style?: any; [key: string]: any }>
  export const Play: Icon
  export const Pause: Icon
  export const Volume2: Icon
  export const Volume1: Icon
  export const VolumeX: Icon
  export const Minus: Icon
  export const Plus: Icon
  export const X: Icon
  export const CheckCircle: Icon
  export const AlertCircle: Icon
  export const Info: Icon
  export const Mic: Icon
  export const Download: Icon
  export const RefreshCcw: Icon
  export const RefreshCw: Icon
  export const Copy: Icon
  export const Check: Icon
  export const User: Icon
  export const Lock: Icon
  export const CreditCard: Icon
  export const Crown: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Sparkles: Icon
  export const Loader2: Icon
  export const XCircle: Icon
  export const Zap: Icon
  export const Cookie: Icon
  export const FileText: Icon
  export const Globe: Icon
  export const Target: Icon
  export const ArrowRight: Icon
  export const TrendingUp: Icon
  export const Users: Icon
  export const Code: Icon
  export const Rocket: Icon
  export const Layout: Icon
  export const Smartphone: Icon
  export const Palette: Icon
  export const Image: Icon
  export const Layers: Icon
  export const Maximize: Icon
  export const Headphones: Icon
  export const Menu: Icon
  export const ChevronDown: Icon
  export const Instagram: Icon
  export const Twitter: Icon
  export const Music2: Icon
  export const Brain: Icon
  export const Waypoints: Icon
  export const Save: Icon
  export const Trash2: Icon
  export const Settings2: Icon
  export const Settings: Icon
  export const SquarePen: Icon
  export const ClipboardList: Icon
  export const Blocks: Icon
  export const Store: Icon
  export const BookOpen: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const Clock: Icon
  export const Activity: Icon
  export const LogOut: Icon
  export const ArrowUp: Icon
  export const ImageIcon: Icon
  export const HistoryIcon: Icon
  export const PauseCircle: Icon
  export const ExternalLink: Icon
  export const LockIcon: Icon
  export const Wand2: Icon
  export const Package: Icon
  export const Type: Icon
  export const Hash: Icon
  export const Star: Icon
  export const Search: Icon
  export const Filter: Icon
  export const Calendar: Icon
  export const History: Icon
  export const Bell: Icon
  export const ZoomIn: Icon
  export const Square: Icon
  export const Maximize2: Icon
  export const Home: Icon
  export const HelpCircle: Icon
  export const HomeIcon: Icon
  export const SettingsIcon: Icon
  export const CreditCardIcon: Icon
  export const LogOutIcon: Icon
  export const UserIcon: Icon
  export const HelpCircleIcon: Icon
  export const RefreshCwIcon: Icon
  export const ArrowUpIcon: Icon
  export const SparklesIcon: Icon
  export const LayoutIcon: Icon
  export const Music2Icon: Icon
  export const MessageCircle: Icon
  export const MessageSquare: Icon
  export const Mail: Icon
  export const SendHorizontal: Icon
  export const Cpu: Icon
  export const Paperclip: Icon
  export const Phone: Icon
  export const Clapperboard: Icon
  export const WandSparkles: Icon
  export const ShieldCheck: Icon
  export const BarChart3: Icon
  export const Shield: Icon
}
